name: company_dashboard
description: MintFlow company admin dashboard built with Flutter Web.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  fl_chart: ^1.2.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_svg: ^2.3.0
  google_fonts: ^8.1.0
  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.4
  http: ^1.2.0
  youtube_player_iframe: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/brand_logo.svg
    - assets/google_logo.svg
