name: company_dashboard
description: MintFlow company admin dashboard built with Flutter Web.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  fl_chart: ^1.2.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  google_fonts: ^8.1.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
