"""add_slides_and_gamification_columns

Revision ID: 190551c35b9b
Revises: d0fff2b05c38
Create Date: 2026-07-04 00:47:18.898576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '190551c35b9b'
down_revision: Union[str, Sequence[str], None] = 'd0fff2b05c38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('slides', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('mint_coins', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('users', sa.Column('coins_earned_today', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('users', sa.Column('raffle_tickets', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('users', sa.Column('daily_streak', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('users', sa.Column('last_earning_reset', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_watch_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_watch_date')
    op.drop_column('users', 'last_earning_reset')
    op.drop_column('users', 'daily_streak')
    op.drop_column('users', 'raffle_tickets')
    op.drop_column('users', 'coins_earned_today')
    op.drop_column('users', 'mint_coins')
    op.drop_column('campaigns', 'slides')
    # ### end Alembic commands ###
