"""add_brand_profile_and_boost_columns

Revision ID: 872fcc238712
Revises: 190551c35b9b
Create Date: 2026-07-04 01:15:34.721979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '872fcc238712'
down_revision: Union[str, Sequence[str], None] = '190551c35b9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('brand_bio', sa.Text(), nullable=True))
    op.add_column('campaigns', sa.Column('brand_website', sa.String(length=500), nullable=True))
    op.add_column('campaigns', sa.Column('brand_logo_url', sa.String(length=500), nullable=True))
    op.add_column('campaigns', sa.Column('is_boosted', sa.Boolean(), nullable=False, server_default="false"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'is_boosted')
    op.drop_column('campaigns', 'brand_logo_url')
    op.drop_column('campaigns', 'brand_website')
    op.drop_column('campaigns', 'brand_bio')
    # ### end Alembic commands ###
