"""add_cta_clicked_to_watch_sessions

Revision ID: d0fff2b05c38
Revises: d34f2339824c
Create Date: 2026-07-03 11:44:02.990865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0fff2b05c38'
down_revision: Union[str, Sequence[str], None] = 'd34f2339824c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watch_sessions', sa.Column('cta_clicked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watch_sessions', 'cta_clicked')
    # ### end Alembic commands ###
