"""add_targeting_and_cta_fields

Revision ID: d34f2339824c
Revises: ef52527ac725
Create Date: 2026-07-02 17:55:56.595249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd34f2339824c'
down_revision: Union[str, Sequence[str], None] = 'ef52527ac725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('cta_url', sa.String(length=500), nullable=True))
    op.add_column('campaigns', sa.Column('cta_button_text', sa.String(length=100), nullable=True))
    op.add_column('campaigns', sa.Column('target_gender', sa.String(length=50), nullable=True))
    op.add_column('campaigns', sa.Column('target_age_min', sa.Integer(), nullable=True))
    op.add_column('campaigns', sa.Column('target_age_max', sa.Integer(), nullable=True))
    op.add_column('campaigns', sa.Column('target_locations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('campaigns', sa.Column('target_interests', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'target_interests')
    op.drop_column('campaigns', 'target_locations')
    op.drop_column('campaigns', 'target_age_max')
    op.drop_column('campaigns', 'target_age_min')
    op.drop_column('campaigns', 'target_gender')
    op.drop_column('campaigns', 'cta_button_text')
    op.drop_column('campaigns', 'cta_url')
    # ### end Alembic commands ###
