"""add_youtube_fields_to_campaigns

Revision ID: ef52527ac725
Revises: 39c5b354a1bc
Create Date: 2026-07-02 13:02:49.377197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef52527ac725'
down_revision: Union[str, Sequence[str], None] = '39c5b354a1bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('youtube_url', sa.String(length=500), nullable=True))
    op.add_column('campaigns', sa.Column('youtube_video_id', sa.String(length=20), nullable=True))
    op.alter_column('campaigns', 'start_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('campaigns', 'end_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_column('campaigns', 'video_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('video_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.alter_column('campaigns', 'end_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('campaigns', 'start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_column('campaigns', 'youtube_video_id')
    op.drop_column('campaigns', 'youtube_url')
    # ### end Alembic commands ###
